### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by sheeplepie** [HX-Rd/namecheap#1]
I would like to use this but there are no setup instructions and the description of installing plugins on the official docs doesn't seem to apply here: https://www.terraform.io/docs/plugins/basics.html

**Comment by HX-Rd** [comment]
Hi @sheeplepie sorry for the very late response. This was written two years ago when the plugin system in terraform was different. @adamdecaf is working on getting the plugin into the new format here  https://github.com/adamdecaf/terraform-provider-namecheap

**Comment by adamdecaf** [comment]
@sheeplepie I've made a [0.1.0 release](https://github.com/adamdecaf/terraform-provider-namecheap/releases/tag/0.1.0).

You can view the [install directions](https://github.com/adamdecaf/terraform-provider-namecheap/tree/0.1.0#namecheap-terraform-provider) for that also. 

Let me know if you've got any questions.
